/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CalendarRouteRouteImport } from './routes/calendar/route'
import { Route as ForgotPasswordRouteRouteImport } from './routes/forgot-password/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as MyEventsRouteRouteImport } from './routes/my-events/route'
import { Route as ResetPasswordRouteRouteImport } from './routes/reset-password/route'
import { Route as SavedRouteRouteImport } from './routes/saved/route'
import { Route as SignupRouteRouteImport } from './routes/signup/route'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as ApiAvailabilityRouteRouteImport } from './routes/api/availability/route'
import { Route as ApiDocsRouteRouteImport } from './routes/api/docs/route'
import { Route as ApiOpenapiDotjsonRouteRouteImport } from './routes/api/openapi[.]json/route'
import { Route as ApiTagsRouteRouteImport } from './routes/api/tags/route'
import { Route as ApiAuthSplatRouteRouteImport } from './routes/api/auth/$/route'
import { Route as ApiEventsIndexRouteImport } from './routes/api/events/index'
import { Route as ApiEventsEventIdRouteRouteImport } from './routes/api/events/$eventId/route'
import { Route as ApiPlacesIndexRouteImport } from './routes/api/places/index'
import { Route as ApiPlacesPlaceIdRouteRouteImport } from './routes/api/places/$placeId/route'
import { Route as ApiV1SplatRouteRouteImport } from './routes/api/v1/$/route'
import { Route as ApiPlacesPlaceIdHoursRouteRouteImport } from './routes/api/places/$placeId/hours/route'
import { Route as ApiEventsEventIdOccurrencesIndexRouteImport } from './routes/api/events/$eventId/occurrences/index'
import { Route as ApiEventsEventIdOccurrencesOccurrenceIdRouteRouteImport } from './routes/api/events/$eventId/occurrences/$occurrenceId/route'
import { Route as ApiEventsEventIdRecurrencesIndexRouteImport } from './routes/api/events/$eventId/recurrences/index'
import { Route as ApiEventsEventIdRecurrencesRecurrenceIdRouteRouteImport } from './routes/api/events/$eventId/recurrences/$recurrenceId/route'
import { Route as ApiPlacesPlaceIdExceptionsIndexRouteImport } from './routes/api/places/$placeId/exceptions/index'
import { Route as ApiPlacesPlaceIdExceptionsDateRouteRouteImport } from './routes/api/places/$placeId/exceptions/$date/route'

const CalendarRouteRoute = CalendarRouteRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRouteRoute = ForgotPasswordRouteRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRouteRoute = MyEventsRouteRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRouteRoute = ResetPasswordRouteRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRouteRoute = SavedRouteRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRouteRoute = SignupRouteRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvailabilityRouteRoute = ApiAvailabilityRouteRouteImport.update({
  id: '/api/availability',
  path: '/api/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRouteRoute = ApiDocsRouteRouteImport.update({
  id: '/api/docs',
  path: '/api/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiDotjsonRouteRoute = ApiOpenapiDotjsonRouteRouteImport.update({
  id: '/api/openapi.json',
  path: '/api/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTagsRouteRoute = ApiTagsRouteRouteImport.update({
  id: '/api/tags',
  path: '/api/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRouteRoute = ApiAuthSplatRouteRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsIndexRoute = ApiEventsIndexRouteImport.update({
  id: '/api/events/',
  path: '/api/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsEventIdRouteRoute = ApiEventsEventIdRouteRouteImport.update({
  id: '/api/events/$eventId',
  path: '/api/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacesIndexRoute = ApiPlacesIndexRouteImport.update({
  id: '/api/places/',
  path: '/api/places/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacesPlaceIdRouteRoute = ApiPlacesPlaceIdRouteRouteImport.update({
  id: '/api/places/$placeId',
  path: '/api/places/$placeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRouteRoute = ApiV1SplatRouteRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacesPlaceIdHoursRouteRoute =
  ApiPlacesPlaceIdHoursRouteRouteImport.update({
    id: '/hours',
    path: '/hours',
    getParentRoute: () => ApiPlacesPlaceIdRouteRoute,
  } as any)
const ApiEventsEventIdOccurrencesIndexRoute =
  ApiEventsEventIdOccurrencesIndexRouteImport.update({
    id: '/occurrences/',
    path: '/occurrences/',
    getParentRoute: () => ApiEventsEventIdRouteRoute,
  } as any)
const ApiEventsEventIdOccurrencesOccurrenceIdRouteRoute =
  ApiEventsEventIdOccurrencesOccurrenceIdRouteRouteImport.update({
    id: '/occurrences/$occurrenceId',
    path: '/occurrences/$occurrenceId',
    getParentRoute: () => ApiEventsEventIdRouteRoute,
  } as any)
const ApiEventsEventIdRecurrencesIndexRoute =
  ApiEventsEventIdRecurrencesIndexRouteImport.update({
    id: '/recurrences/',
    path: '/recurrences/',
    getParentRoute: () => ApiEventsEventIdRouteRoute,
  } as any)
const ApiEventsEventIdRecurrencesRecurrenceIdRouteRoute =
  ApiEventsEventIdRecurrencesRecurrenceIdRouteRouteImport.update({
    id: '/recurrences/$recurrenceId',
    path: '/recurrences/$recurrenceId',
    getParentRoute: () => ApiEventsEventIdRouteRoute,
  } as any)
const ApiPlacesPlaceIdExceptionsIndexRoute =
  ApiPlacesPlaceIdExceptionsIndexRouteImport.update({
    id: '/exceptions/',
    path: '/exceptions/',
    getParentRoute: () => ApiPlacesPlaceIdRouteRoute,
  } as any)
const ApiPlacesPlaceIdExceptionsDateRouteRoute =
  ApiPlacesPlaceIdExceptionsDateRouteRouteImport.update({
    id: '/exceptions/$date',
    path: '/exceptions/$date',
    getParentRoute: () => ApiPlacesPlaceIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/calendar': typeof CalendarRouteRoute
  '/forgot-password': typeof ForgotPasswordRouteRoute
  '/login': typeof LoginRouteRoute
  '/my-events': typeof MyEventsRouteRoute
  '/reset-password': typeof ResetPasswordRouteRoute
  '/saved': typeof SavedRouteRoute
  '/signup': typeof SignupRouteRoute
  '/api/availability': typeof ApiAvailabilityRouteRoute
  '/api/docs': typeof ApiDocsRouteRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRouteRoute
  '/api/tags': typeof ApiTagsRouteRoute
  '/': typeof homeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRouteRoute
  '/api/events/$eventId': typeof ApiEventsEventIdRouteRouteWithChildren
  '/api/places/$placeId': typeof ApiPlacesPlaceIdRouteRouteWithChildren
  '/api/v1/$': typeof ApiV1SplatRouteRoute
  '/api/events/': typeof ApiEventsIndexRoute
  '/api/places/': typeof ApiPlacesIndexRoute
  '/api/places/$placeId/hours': typeof ApiPlacesPlaceIdHoursRouteRoute
  '/api/events/$eventId/occurrences/$occurrenceId': typeof ApiEventsEventIdOccurrencesOccurrenceIdRouteRoute
  '/api/events/$eventId/recurrences/$recurrenceId': typeof ApiEventsEventIdRecurrencesRecurrenceIdRouteRoute
  '/api/places/$placeId/exceptions/$date': typeof ApiPlacesPlaceIdExceptionsDateRouteRoute
  '/api/events/$eventId/occurrences/': typeof ApiEventsEventIdOccurrencesIndexRoute
  '/api/events/$eventId/recurrences/': typeof ApiEventsEventIdRecurrencesIndexRoute
  '/api/places/$placeId/exceptions/': typeof ApiPlacesPlaceIdExceptionsIndexRoute
}
export interface FileRoutesByTo {
  '/calendar': typeof CalendarRouteRoute
  '/forgot-password': typeof ForgotPasswordRouteRoute
  '/login': typeof LoginRouteRoute
  '/my-events': typeof MyEventsRouteRoute
  '/reset-password': typeof ResetPasswordRouteRoute
  '/saved': typeof SavedRouteRoute
  '/signup': typeof SignupRouteRoute
  '/api/availability': typeof ApiAvailabilityRouteRoute
  '/api/docs': typeof ApiDocsRouteRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRouteRoute
  '/api/tags': typeof ApiTagsRouteRoute
  '/': typeof homeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRouteRoute
  '/api/events/$eventId': typeof ApiEventsEventIdRouteRouteWithChildren
  '/api/places/$placeId': typeof ApiPlacesPlaceIdRouteRouteWithChildren
  '/api/v1/$': typeof ApiV1SplatRouteRoute
  '/api/events': typeof ApiEventsIndexRoute
  '/api/places': typeof ApiPlacesIndexRoute
  '/api/places/$placeId/hours': typeof ApiPlacesPlaceIdHoursRouteRoute
  '/api/events/$eventId/occurrences/$occurrenceId': typeof ApiEventsEventIdOccurrencesOccurrenceIdRouteRoute
  '/api/events/$eventId/recurrences/$recurrenceId': typeof ApiEventsEventIdRecurrencesRecurrenceIdRouteRoute
  '/api/places/$placeId/exceptions/$date': typeof ApiPlacesPlaceIdExceptionsDateRouteRoute
  '/api/events/$eventId/occurrences': typeof ApiEventsEventIdOccurrencesIndexRoute
  '/api/events/$eventId/recurrences': typeof ApiEventsEventIdRecurrencesIndexRoute
  '/api/places/$placeId/exceptions': typeof ApiPlacesPlaceIdExceptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/calendar': typeof CalendarRouteRoute
  '/forgot-password': typeof ForgotPasswordRouteRoute
  '/login': typeof LoginRouteRoute
  '/my-events': typeof MyEventsRouteRoute
  '/reset-password': typeof ResetPasswordRouteRoute
  '/saved': typeof SavedRouteRoute
  '/signup': typeof SignupRouteRoute
  '/api/availability': typeof ApiAvailabilityRouteRoute
  '/api/docs': typeof ApiDocsRouteRoute
  '/api/openapi.json': typeof ApiOpenapiDotjsonRouteRoute
  '/api/tags': typeof ApiTagsRouteRoute
  '/(home)/': typeof homeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRouteRoute
  '/api/events/$eventId': typeof ApiEventsEventIdRouteRouteWithChildren
  '/api/places/$placeId': typeof ApiPlacesPlaceIdRouteRouteWithChildren
  '/api/v1/$': typeof ApiV1SplatRouteRoute
  '/api/events/': typeof ApiEventsIndexRoute
  '/api/places/': typeof ApiPlacesIndexRoute
  '/api/places/$placeId/hours': typeof ApiPlacesPlaceIdHoursRouteRoute
  '/api/events/$eventId/occurrences/$occurrenceId': typeof ApiEventsEventIdOccurrencesOccurrenceIdRouteRoute
  '/api/events/$eventId/recurrences/$recurrenceId': typeof ApiEventsEventIdRecurrencesRecurrenceIdRouteRoute
  '/api/places/$placeId/exceptions/$date': typeof ApiPlacesPlaceIdExceptionsDateRouteRoute
  '/api/events/$eventId/occurrences/': typeof ApiEventsEventIdOccurrencesIndexRoute
  '/api/events/$eventId/recurrences/': typeof ApiEventsEventIdRecurrencesIndexRoute
  '/api/places/$placeId/exceptions/': typeof ApiPlacesPlaceIdExceptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/calendar'
    | '/forgot-password'
    | '/login'
    | '/my-events'
    | '/reset-password'
    | '/saved'
    | '/signup'
    | '/api/availability'
    | '/api/docs'
    | '/api/openapi.json'
    | '/api/tags'
    | '/'
    | '/api/auth/$'
    | '/api/events/$eventId'
    | '/api/places/$placeId'
    | '/api/v1/$'
    | '/api/events/'
    | '/api/places/'
    | '/api/places/$placeId/hours'
    | '/api/events/$eventId/occurrences/$occurrenceId'
    | '/api/events/$eventId/recurrences/$recurrenceId'
    | '/api/places/$placeId/exceptions/$date'
    | '/api/events/$eventId/occurrences/'
    | '/api/events/$eventId/recurrences/'
    | '/api/places/$placeId/exceptions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/calendar'
    | '/forgot-password'
    | '/login'
    | '/my-events'
    | '/reset-password'
    | '/saved'
    | '/signup'
    | '/api/availability'
    | '/api/docs'
    | '/api/openapi.json'
    | '/api/tags'
    | '/'
    | '/api/auth/$'
    | '/api/events/$eventId'
    | '/api/places/$placeId'
    | '/api/v1/$'
    | '/api/events'
    | '/api/places'
    | '/api/places/$placeId/hours'
    | '/api/events/$eventId/occurrences/$occurrenceId'
    | '/api/events/$eventId/recurrences/$recurrenceId'
    | '/api/places/$placeId/exceptions/$date'
    | '/api/events/$eventId/occurrences'
    | '/api/events/$eventId/recurrences'
    | '/api/places/$placeId/exceptions'
  id:
    | '__root__'
    | '/calendar'
    | '/forgot-password'
    | '/login'
    | '/my-events'
    | '/reset-password'
    | '/saved'
    | '/signup'
    | '/api/availability'
    | '/api/docs'
    | '/api/openapi.json'
    | '/api/tags'
    | '/(home)/'
    | '/api/auth/$'
    | '/api/events/$eventId'
    | '/api/places/$placeId'
    | '/api/v1/$'
    | '/api/events/'
    | '/api/places/'
    | '/api/places/$placeId/hours'
    | '/api/events/$eventId/occurrences/$occurrenceId'
    | '/api/events/$eventId/recurrences/$recurrenceId'
    | '/api/places/$placeId/exceptions/$date'
    | '/api/events/$eventId/occurrences/'
    | '/api/events/$eventId/recurrences/'
    | '/api/places/$placeId/exceptions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CalendarRouteRoute: typeof CalendarRouteRoute
  ForgotPasswordRouteRoute: typeof ForgotPasswordRouteRoute
  LoginRouteRoute: typeof LoginRouteRoute
  MyEventsRouteRoute: typeof MyEventsRouteRoute
  ResetPasswordRouteRoute: typeof ResetPasswordRouteRoute
  SavedRouteRoute: typeof SavedRouteRoute
  SignupRouteRoute: typeof SignupRouteRoute
  ApiAvailabilityRouteRoute: typeof ApiAvailabilityRouteRoute
  ApiDocsRouteRoute: typeof ApiDocsRouteRoute
  ApiOpenapiDotjsonRouteRoute: typeof ApiOpenapiDotjsonRouteRoute
  ApiTagsRouteRoute: typeof ApiTagsRouteRoute
  homeIndexRoute: typeof homeIndexRoute
  ApiAuthSplatRouteRoute: typeof ApiAuthSplatRouteRoute
  ApiEventsEventIdRouteRoute: typeof ApiEventsEventIdRouteRouteWithChildren
  ApiPlacesPlaceIdRouteRoute: typeof ApiPlacesPlaceIdRouteRouteWithChildren
  ApiV1SplatRouteRoute: typeof ApiV1SplatRouteRoute
  ApiEventsIndexRoute: typeof ApiEventsIndexRoute
  ApiPlacesIndexRoute: typeof ApiPlacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/availability': {
      id: '/api/availability'
      path: '/api/availability'
      fullPath: '/api/availability'
      preLoaderRoute: typeof ApiAvailabilityRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs': {
      id: '/api/docs'
      path: '/api/docs'
      fullPath: '/api/docs'
      preLoaderRoute: typeof ApiDocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi.json': {
      id: '/api/openapi.json'
      path: '/api/openapi.json'
      fullPath: '/api/openapi.json'
      preLoaderRoute: typeof ApiOpenapiDotjsonRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tags': {
      id: '/api/tags'
      path: '/api/tags'
      fullPath: '/api/tags'
      preLoaderRoute: typeof ApiTagsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/': {
      id: '/api/events/'
      path: '/api/events'
      fullPath: '/api/events/'
      preLoaderRoute: typeof ApiEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/$eventId': {
      id: '/api/events/$eventId'
      path: '/api/events/$eventId'
      fullPath: '/api/events/$eventId'
      preLoaderRoute: typeof ApiEventsEventIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/places/': {
      id: '/api/places/'
      path: '/api/places'
      fullPath: '/api/places/'
      preLoaderRoute: typeof ApiPlacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/places/$placeId': {
      id: '/api/places/$placeId'
      path: '/api/places/$placeId'
      fullPath: '/api/places/$placeId'
      preLoaderRoute: typeof ApiPlacesPlaceIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/places/$placeId/hours': {
      id: '/api/places/$placeId/hours'
      path: '/hours'
      fullPath: '/api/places/$placeId/hours'
      preLoaderRoute: typeof ApiPlacesPlaceIdHoursRouteRouteImport
      parentRoute: typeof ApiPlacesPlaceIdRouteRoute
    }
    '/api/events/$eventId/occurrences/': {
      id: '/api/events/$eventId/occurrences/'
      path: '/occurrences'
      fullPath: '/api/events/$eventId/occurrences/'
      preLoaderRoute: typeof ApiEventsEventIdOccurrencesIndexRouteImport
      parentRoute: typeof ApiEventsEventIdRouteRoute
    }
    '/api/events/$eventId/occurrences/$occurrenceId': {
      id: '/api/events/$eventId/occurrences/$occurrenceId'
      path: '/occurrences/$occurrenceId'
      fullPath: '/api/events/$eventId/occurrences/$occurrenceId'
      preLoaderRoute: typeof ApiEventsEventIdOccurrencesOccurrenceIdRouteRouteImport
      parentRoute: typeof ApiEventsEventIdRouteRoute
    }
    '/api/events/$eventId/recurrences/': {
      id: '/api/events/$eventId/recurrences/'
      path: '/recurrences'
      fullPath: '/api/events/$eventId/recurrences/'
      preLoaderRoute: typeof ApiEventsEventIdRecurrencesIndexRouteImport
      parentRoute: typeof ApiEventsEventIdRouteRoute
    }
    '/api/events/$eventId/recurrences/$recurrenceId': {
      id: '/api/events/$eventId/recurrences/$recurrenceId'
      path: '/recurrences/$recurrenceId'
      fullPath: '/api/events/$eventId/recurrences/$recurrenceId'
      preLoaderRoute: typeof ApiEventsEventIdRecurrencesRecurrenceIdRouteRouteImport
      parentRoute: typeof ApiEventsEventIdRouteRoute
    }
    '/api/places/$placeId/exceptions/': {
      id: '/api/places/$placeId/exceptions/'
      path: '/exceptions'
      fullPath: '/api/places/$placeId/exceptions/'
      preLoaderRoute: typeof ApiPlacesPlaceIdExceptionsIndexRouteImport
      parentRoute: typeof ApiPlacesPlaceIdRouteRoute
    }
    '/api/places/$placeId/exceptions/$date': {
      id: '/api/places/$placeId/exceptions/$date'
      path: '/exceptions/$date'
      fullPath: '/api/places/$placeId/exceptions/$date'
      preLoaderRoute: typeof ApiPlacesPlaceIdExceptionsDateRouteRouteImport
      parentRoute: typeof ApiPlacesPlaceIdRouteRoute
    }
  }
}

interface ApiEventsEventIdRouteRouteChildren {
  ApiEventsEventIdOccurrencesOccurrenceIdRouteRoute: typeof ApiEventsEventIdOccurrencesOccurrenceIdRouteRoute
  ApiEventsEventIdRecurrencesRecurrenceIdRouteRoute: typeof ApiEventsEventIdRecurrencesRecurrenceIdRouteRoute
  ApiEventsEventIdOccurrencesIndexRoute: typeof ApiEventsEventIdOccurrencesIndexRoute
  ApiEventsEventIdRecurrencesIndexRoute: typeof ApiEventsEventIdRecurrencesIndexRoute
}

const ApiEventsEventIdRouteRouteChildren: ApiEventsEventIdRouteRouteChildren = {
  ApiEventsEventIdOccurrencesOccurrenceIdRouteRoute:
    ApiEventsEventIdOccurrencesOccurrenceIdRouteRoute,
  ApiEventsEventIdRecurrencesRecurrenceIdRouteRoute:
    ApiEventsEventIdRecurrencesRecurrenceIdRouteRoute,
  ApiEventsEventIdOccurrencesIndexRoute: ApiEventsEventIdOccurrencesIndexRoute,
  ApiEventsEventIdRecurrencesIndexRoute: ApiEventsEventIdRecurrencesIndexRoute,
}

const ApiEventsEventIdRouteRouteWithChildren =
  ApiEventsEventIdRouteRoute._addFileChildren(
    ApiEventsEventIdRouteRouteChildren,
  )

interface ApiPlacesPlaceIdRouteRouteChildren {
  ApiPlacesPlaceIdHoursRouteRoute: typeof ApiPlacesPlaceIdHoursRouteRoute
  ApiPlacesPlaceIdExceptionsDateRouteRoute: typeof ApiPlacesPlaceIdExceptionsDateRouteRoute
  ApiPlacesPlaceIdExceptionsIndexRoute: typeof ApiPlacesPlaceIdExceptionsIndexRoute
}

const ApiPlacesPlaceIdRouteRouteChildren: ApiPlacesPlaceIdRouteRouteChildren = {
  ApiPlacesPlaceIdHoursRouteRoute: ApiPlacesPlaceIdHoursRouteRoute,
  ApiPlacesPlaceIdExceptionsDateRouteRoute:
    ApiPlacesPlaceIdExceptionsDateRouteRoute,
  ApiPlacesPlaceIdExceptionsIndexRoute: ApiPlacesPlaceIdExceptionsIndexRoute,
}

const ApiPlacesPlaceIdRouteRouteWithChildren =
  ApiPlacesPlaceIdRouteRoute._addFileChildren(
    ApiPlacesPlaceIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  CalendarRouteRoute: CalendarRouteRoute,
  ForgotPasswordRouteRoute: ForgotPasswordRouteRoute,
  LoginRouteRoute: LoginRouteRoute,
  MyEventsRouteRoute: MyEventsRouteRoute,
  ResetPasswordRouteRoute: ResetPasswordRouteRoute,
  SavedRouteRoute: SavedRouteRoute,
  SignupRouteRoute: SignupRouteRoute,
  ApiAvailabilityRouteRoute: ApiAvailabilityRouteRoute,
  ApiDocsRouteRoute: ApiDocsRouteRoute,
  ApiOpenapiDotjsonRouteRoute: ApiOpenapiDotjsonRouteRoute,
  ApiTagsRouteRoute: ApiTagsRouteRoute,
  homeIndexRoute: homeIndexRoute,
  ApiAuthSplatRouteRoute: ApiAuthSplatRouteRoute,
  ApiEventsEventIdRouteRoute: ApiEventsEventIdRouteRouteWithChildren,
  ApiPlacesPlaceIdRouteRoute: ApiPlacesPlaceIdRouteRouteWithChildren,
  ApiV1SplatRouteRoute: ApiV1SplatRouteRoute,
  ApiEventsIndexRoute: ApiEventsIndexRoute,
  ApiPlacesIndexRoute: ApiPlacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
