name: Delete Neon Branch

on:
  delete:

permissions:
  contents: read

jobs:
  delete-neon-branch:
    name: Delete Neon Branch
    if: |
      github.event.ref_type == 'branch' &&
      github.event.ref != 'development' &&
      github.event.ref != 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Delete Neon preview branch
        uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch: preview/${{ github.event.ref }}
          api_key: ${{ secrets.NEON_API_KEY }}
